### ISSUE TITLE
Fix:sumiu tudo

### ISSUE THREAD

**Issue by DanielDeSousaDEV** [Gabriel-Sousa-Dev/testeIssue#1]
### deu errado ;-; 👍🏼
**markdown** como ferramenta de conversão de texto para HTML, linguagem usada para criar páginas da web.
Texto _torto_.

> Quoted text
> English 🧐

`cd pastalegal/`

**Comment by DanielDeSousaDEV** [comment]
- [ ] marque quando terminar
- [x] marque quando não tiver terminado

@Gabriel-Sousa-Dev vai estudar

<details><summary>Details</summary>
<p>

Aaaaaaaaaaaaaaaa

</p>
</details>

**Comment by Gabriel-Sousa-Dev** [comment]
Beisso
